apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: moderneci-app
  namespace: argocd
spec:
  project: moderneci
  source:
    repoURL: https://github.com/mombe090/moderneci.git
    targetRevision: main
    path: helmChart
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: app-maven
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      