apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: moderneci
  namespace: argocd
spec:
  description: Projet ArgoCd pour le déploiement de ModernECI
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'