management:
  metrics:
    tags:
      application: {{ .Release.Name }}-{{ .Release.Namespace }}
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,caches,metrics
      health:
        probes:
          enabled: true

spring:
  application:
    name: {{ .Release.Name }}
